api:
  build: .
  command: node /smd_api/index.js --restart=always
  ports:
    - "3000:3000"
  links:
    - rethinkdb
rethinkdb:
  image: rethinkdb
  ports:
    - "8080:8080"
    - "28015:28015"
    - "29015:29015"